services:
  api:
    build: ./Backend
    container_name: api_rate_limiter
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./Backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./Backend/.env

  postgres:
    image: postgres:15
    container_name: api_rate_db
    env_file:
      - ./Backend/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: api_rate_cache
    ports:
      - "6379:6379"
  frontend:
    build: ./Frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

volumes:
  postgres-db: